### PR TITLE
CLDR 38.1.0

### PR DESCRIPTION
**Pull request by srl295**
This PR is now ready to be the *final* data. Please review.

-----
Beta build:

- https://github.com/unicode-org/cldr-json/releases/tag/38.1.0-BETA
- downloadable at https://github.com/unicode-org/cldr/releases/tag/release-38-1-beta also

### CODE REVIEW

**Review by pedberg-icu — APPROVED** [review]

**Comment by srl295** [comment]
updated for BETA3

**Comment by srl295** [comment]
tagged this as `38.1.0-BETA4`

**Comment by srl295** [comment]
Need to merge 38.1 final here

**Review by sffc — COMMENTED** [review]
Is it only a coincidence that the only locales updated are early in the alphabet, from af through ccp?  Or did the tool crash or something and not finish updating locales after ccp?

**Review by sffc — APPROVED** [review]
Never mind; it's loaded now.  It just took a long time for the 3,545,580 lines to load (😲).

**Pull request merged**
