### PR TITLE
CLDR-15443 fix path to LICENSE file in generated .zip

### PR DESCRIPTION
**Pull request by robertbastian**
fix path to LICENSE file in generated .zip

### CODE REVIEW

**Comment by srl295** [comment]
@robertbastian thanks

**Comment by robertbastian** [comment]
Could we get this into a release?

**Review by rickmcgowan — COMMENTED** [review]
Looks like a reasonable way to get the ../LICENSE file into ./ for zipping.

**Review by srl295 — COMMENTED** [review]
i also had reviewed this.

**Comment by srl295** [comment]
I just released 41.0.0-BETA2 check the releases page of the repo

**Comment by robertbastian** [comment]
This already is in 41 as well.

**Comment by robertbastian** [comment]
Ah this had me really confused.

**Comment by srl295** [comment]
> Ah this had me really confused.

me too. no idea how that happened.

**Comment by srl295** [comment]
but while you're here: https://github.com/unicode-org/cldr-json/releases/tag/v42.0.0-BETA3

**Comment by robertbastian** [comment]
Yes I just tried that because I thought that's what the email was about :)

**Pull request merged**
