### PR TITLE
CLDR-17972 Generate cldr-json 46.0.0-BETA2

### PR DESCRIPTION
**Pull request by btangmu**
-This is run against branch v46, not main

### CODE REVIEW

**Review by btangmu — COMMENTED** [review]
@srl how does this look?

**Comment by btangmu** [comment]
@srl295 how does this look?

**Comment by srl295** [comment]
Spot checks look OK but `cldr-transforms` is missing, did it just not get checked in?

What I recommend is `rm -rf cldr-json` to delete all of cldr-json, and then after generation `git add cldr-json` to add everything

By the way you can run `cldr-identify.sh` to show what your sources are.

**Comment by btangmu** [comment]
> Spot checks look OK but `cldr-transforms` is missing, did it just not get checked in?

I don't know what `cldr-transforms` is. What is it? Where would I find it?
 
> What I recommend is `rm -rf cldr-json` to delete all of cldr-json, and then after generation `git add cldr-json` to add everything

That's what I did, except that I dragged the nested cldr-json to the trash. The effect should be the same.

> By the way you can run `cldr-identify.sh` to show what your sources are.

```
 $ sh cldr-identify.sh
Using local-config.sh
* cldr-json info
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
- DATA: unicode-org/cldr-staging: 
- TOOL: unicode-org/cldr:  b28b9ab8d9 release-46-beta1-4-gb28b9ab8d9
- SCRIPT: unicode-org/cldr-json:  4c478d4819 46.0.0-ALPHA3-1-g4c478d4819
```

Here's how I obtained cldr-staging:

* Go to https://github.com/unicode-org/cldr-staging/releases/tag/release-46-beta2 

* Download cldr-staging-release-46-beta2.zip

* Unzip and rename to cldr-staging

**Comment by btangmu** [comment]
`$ find . -name "cldr-transforms" -print` finds nothing

**Comment by srl295** [comment]
cldr-staging can also be fetched from the repository. I'll see if i can reproduce the data build

**Comment by srl295** [comment]
@btangmu 

> `- TOOL: unicode-org/cldr:  b28b9ab8d9 release-46-beta1-4-gb28b9ab8d9`

the copy of CLDR used is from Sept 18th (per the commit)

**Comment by btangmu** [comment]
@srl295 yesterday I did `git checkout main`, `git fetch upstream` and `git pull`. At that time main was on 54ee48bc85f214bf53fc7868ebb6ac032aac43d7 committed the same day. Now `git pull` reports `Already up to date.` I must have left something out but I don't know what.

**Comment by btangmu** [comment]
@srl295 FYI, it turns out that this would have gotten main up to date:

`git reset --hard upstream/main`

I have that in the script I ordinarily run when I start a new branch. It's unusual for me to work directly with main branch locally and I wrongly thought it would suffice to do `git checkout main`, `git fetch upstream` and `git pull`. Sorry for the confusion, and thanks for taking charge. Let's think about how to make the process more foolproof -- maybe with a script that requires specifying the git hash, similar to push-to-production

**Comment by srl295** [comment]
That's what the identify script is for is to show the provenance 

Actually it was the beta2 tag that was needed not main in this case.

**Pull request closed without merging**
