### PR TITLE
CLDR-17284: v44.1

### PR DESCRIPTION
**Pull request by srl295**

### CODE REVIEW

**Review by btangmu — APPROVED** [review]
rubber stamp LGTM :-)

**Comment by trevisanweb** [comment]
cldr-core remains at version 44.0.1

**Comment by srl295** [comment]
I’ll check

**Comment by srl295** [comment]
Felipe, can you file a ticket for this?

**Comment by trevisanweb** [comment]
Ticket created
https://unicode-org.atlassian.net/browse/CLDR-17292

**Comment by srl295** [comment]
> Ticket created https://unicode-org.atlassian.net/browse/CLDR-17292

🤦 it looks like somehow `cldr-core` (critical as it is!) simply missed being npm published along with the other 42 packages.   It's fixed now. THANK YOU for reporting this, next time please go ahead and file a ticket if something seems amiss so everyone can see it. 

By the way, thanks for using cldr-json! Feel free to PR your project into https://github.com/unicode-org/cldr-json/blob/main/USERS.md if applicable

**Pull request merged**
