### PR TITLE
improve formatting of README, add relevant links

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by JCEmmons** [comment]
Thanks for the changes to the README.  After having to split all the packages out to their own repositories, I realized that the README needs even more work, but this is indeed a good start. Thanks.

**Comment by waldyrious** [comment]
Agreed. I started editing the file with the intention of linking to each of the packages, but realized it would be a much larger/drastic change if I wanted the list to be comprehensive, so I decided to start small since I wasn't sure how you were planning to handle contributions to the repo. Let me know if there's anything else I can help with -- perhaps a table display of the various packages & versions (full/modern)?

**Comment by JCEmmons** [comment]
Take a look at the current readme and let me know what you think. I went ahead and added additional links for all the supported package types, so I think what we have is pretty workable.

**Comment by waldyrious** [comment]
Very nice set of changes indeed, particularly the use of query links -- that's a much better implementation than what I had suggested. I can't see anything else in the README to improve, except perhaps replace "in the packages described" with "in the packages described below", with an anchor link to the Package Organization section.

**Pull request merged**
