### PR TITLE
CLDR-14571 generate cldr-bcp47 data

### PR DESCRIPTION
**Pull request by nordzilla**
CLDR-14571

- [x] This PR completes the ticket.

Generates bcp47 data for cldr-json.

This depends on https://github.com/unicode-org/cldr/pull/1459

### CODE REVIEW

**Comment by sffc** [comment]
Do you need to add the new JSON files to the repo, or is that a separate step?

**Comment by nordzilla** [comment]
@sffc 

> Do you need to add the new JSON files to the repo, or is that a separate step?

I don't believe so. We are still ironing out the details of the directory structure and generation on unicode-org/cldr#1459, but @srl295 said, "I’ll be producing the cldr-json data as a matter of course, pretty soon. So you don’t need to do anything else there."

**Review by srl295 — APPROVED** [review]
LGTM but let's wait until the dependent lands

**Comment by srl295** [comment]
> Do you need to add the new JSON files to the repo, or is that a separate step?

They'll be picked up when I generate candidate data from the CLDR alpha data.

**Pull request merged**
