### PR TITLE
CLDR-18178 Generate cldr-json 46.1.0-BETA1

### PR DESCRIPTION
**Pull request by btangmu**
-Built with cldr tags/release-46-1-beta1 (a3eef1eb57)

-Built with cldr-staging tags/release-46-1-beta1 (downloaded as cldr-release-46-1-beta1.zip)

### CODE REVIEW

**Comment by btangmu** [comment]
@srl295 This is targeting main; is that right? Also, these warnings were shown:

```
$ sh cldr-generate-json.sh
Using local-config.sh
...
[INFO] Storing buildNumber: a3eef1eb5779c88bcc3fe2de63675ff04b5a8bf1 at timestamp: 1733869083016
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref

...
📍 main (step 1/8)	[100%]:	 ✅Completed parallel process of 1,067 files
⚠️ Warning: 342 files did not produce any output (check JSON config):
	- main/rw_RW
	- main/af_ZA
	- main/ve_ZA
...
	- main/gu_IN
📦 Creating packaging file => ./cldr-json/cldr-core/defaultContent.json
📦 Creating packaging file => ./cldr-json/cldr-core/availableLocales.json
📦 Creating packaging file => ./cldr-json/cldr-core/coverageLevels.json from coverageLevels.txt
📂 main	Finished in 55 sec, 3 min


📂#######################  supplemental #######################
📍 supplemental (step 2/8)	[000%]:	 ⚙️ Beginning parallel process of 17 files
📍 supplemental (step 2/8)	[006%]:	rgScope     	∅ (no output)
	    97     numberingSystems /cldr-core/supplemental/numberingSystems.json
📍 supplemental (step 2/8)	[059%]:	numberingSystems	  (97 values in 1 section)
Warning: Duplicate attribute yi in //cldr/supplemental/plurals[@type="cardinal"]/pluralRules[@locales="ast de en et fi fy gl ia io yi lij nl sc sv sw ur yi"]/pluralRule[@_q="5"][@count="one"]
Warning: Duplicate attribute yi in //cldr/supplemental/plurals[@type="cardinal"]/pluralRules[@locales="ast de en et fi fy gl ia io yi lij nl sc sv sw ur yi"]/pluralRule[@_q="6"][@count="other"]
Warning: Duplicate attribute id in //cldr/supplemental/plurals[@type="cardinal"]/pluralRules[@locales="bm bo dz hnj id ig ii id ja jbo jv jw kde kea km ko lkt lo ms my nqo osa und sah ses sg su th to tpi vi wo yo yue zh"]/pluralRule[@_q="0"][@count="other"]
Warning: Duplicate attribute he in //cldr/supplemental/plurals[@type="cardinal"]/pluralRules[@locales="he he"]/pluralRule[@_q="35"][@count="one"]
Warning: Duplicate attribute he in //cldr/supplemental/plurals[@type="cardinal"]/pluralRules[@locales="he he"]/pluralRule[@_q="36"][@count="two"]
Warning: Duplicate attribute he in //cldr/supplemental/plurals[@type="cardinal"]/pluralRules[@locales="he he"]/pluralRule[@_q="37"][@count="other"]
	   169  grammaticalFeatures /cldr-core/supplemental/grammaticalFeatures.json
...
📍 supplemental (step 2/8)	[076%]:	genderList  	  (56 values in 1 section)
Warning: Duplicate attribute id in //cldr/supplemental/plurals[@type="ordinal"]/pluralRules[@locales="af am an ar ast bg bs ce cs da de dsb el es et eu fa fi fy gl gsw he hr hsb ia id id is he ja km kn ko ky lt lv ml mn my nb nl no pa pl prg ps pt und ru sd sh si sk sl sr sw ta te th tpi tr ur uz yue zh zu"]/pluralRule[@_q="0"][@count="other"]
Warning: Duplicate attribute he in //cldr/supplemental/plurals[@type="ordinal"]/pluralRules[@locales="af am an ar ast bg bs ce cs da de dsb el es et eu fa fi fy gl gsw he hr hsb ia id id is he ja km kn ko ky lt lv ml mn my nb nl no pa pl prg ps pt und ru sd sh si sk sl sr sw ta te th tpi tr ur uz yue zh zu"]/pluralRule[@_q="0"][@count="other"]
	   501         windowsZones /cldr-core/supplemental/windowsZones.json
...

📍 supplemental (step 2/8)	[100%]:	supplementalData	  (5,241 values in 13 sections)
Dec. 10, 2024 5:22:01 P.M. org.unicode.cldr.json.Ldml2JsonConverter transformPath
WARNING: Including aliased likelySubtags: //cldr/supplemental/likelySubtags/likelySubtag[@from="in"]
Dec. 10, 2024 5:22:01 P.M. org.unicode.cldr.json.Ldml2JsonConverter transformPath
WARNING: Including aliased likelySubtags: //cldr/supplemental/likelySubtags/likelySubtag[@from="in"][@to="in-Latn-ID"]
Dec. 10, 2024 5:22:01 P.M. org.unicode.cldr.json.Ldml2JsonConverter transformPath
WARNING: Including aliased likelySubtags: //cldr/supplemental/likelySubtags/likelySubtag[@from="iw"]
Dec. 10, 2024 5:22:01 P.M. org.unicode.cldr.json.Ldml2JsonConverter transformPath
WARNING: Including aliased likelySubtags: //cldr/supplemental/likelySubtags/likelySubtag[@from="iw"][@to="iw-Hebr-IL"]
Dec. 10, 2024 5:22:01 P.M. org.unicode.cldr.json.Ldml2JsonConverter transformPath
WARNING: Including aliased likelySubtags: //cldr/supplemental/likelySubtags/likelySubtag[@from="ji"]
Dec. 10, 2024 5:22:01 P.M. org.unicode.cldr.json.Ldml2JsonConverter transformPath
WARNING: Including aliased likelySubtags: //cldr/supplemental/likelySubtags/likelySubtag[@from="ji"][@to="ji-Hebr-UA"]
	  7738        likelySubtags /cldr-core/supplemental/likelySubtags.json
📍 supplemental (step 2/8)	[100%]:	likelySubtags	  (7,738 values in 1 section)
📍 supplemental (step 2/8)	[100%]:	 ✅Completed parallel process of 17 files
⚠️ Warning: 1 file did not produce any output (check JSON config):
	- supplemental/rgScope
Creating script metadata file => ./cldr-json/cldr-core/scriptMetadata.json
...
📍 segments (step 3/8)	[100%]:	 ✅Completed parallel process of 16 files
⚠️ Warning: 2 files did not produce any output (check JSON config):
	- segments/en_US
	- segments/en_US_POSIX ❎ (Skipped due to '-T true': und-US-u-va-posix)
📂 segments	Finished in 0 sec, 0 min
...
📍 rbnf (step 4/8)	[100%]:	 ✅Completed parallel process of 90 files
⚠️ Warning: 2 files did not produce any output (check JSON config):
	- rbnf/en_001
	- rbnf/nb
📂 rbnf	Finished in 0 sec, 0 min
...
📍 annotations (step 5/8)	[100%]:	 ✅Completed parallel process of 167 files
⚠️ Warning: 1 file did not produce any output (check JSON config):
	- annotations/ca_ES
📂 annotations	Finished in 10 sec, 0 mi
...
📍 annotationsDerived (step 6/8)	[100%]:	 ✅Completed parallel process of 166 files
⚠️ Warning: 1 file did not produce any output (check JSON config):
	- annotationsDerived/ca_ES
📂 annotationsDerived	Finished in 15 sec, 0 min
...
📍 transforms (step 8/8)	[100%]:	 ✅Completed parallel process of 379 files
⚠️ Warning: 5 files did not produce any output (check JSON config):
	- transforms/ug-Latin
	- transforms/Sinhala-Latin
	- transforms/Japn-Latn
	- transforms/Khmer-Latin
	- transforms/Lao-Latin
📦 Creating packaging file => ./cldr-json/cldr-transforms/transforms.json
📂 transforms	Finished in 0 sec, 0 min



###

✅ Finished everything in 25 sec, 4 min
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:25 min
[INFO] Finished at: 2024-12-10T17:22:29-05:00
[INFO] ------------------------------------------------------------------------
+ echo 'Finshed converting '\''all'\'' to ./cldr-json'
Finshed converting 'all' to ./cldr-json
+ '[' -x ./local-config.sh ']'
+ echo 'REMINDER: you have a local-config.sh - may not be a standard build'
REMINDER: you have a local-config.sh - may not be a standard build
```

**Comment by srl295** [comment]
Main is right and warnings look expected. Shouldn't be files added or removed.

**Comment by srl295** [comment]
Main is right and warnings look expected. Shouldn't be files added or removed.

**Comment by srl295** [comment]
obviated by #79

**Pull request closed without merging**
